#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : capturer
Version  : 2.4
Release  : 1
URL      : https://files.pythonhosted.org/packages/ce/a4/fabb849584366383a59d2ac985a7ece30609f1ae4a40ecfd02baad900a2d/capturer-2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/a4/fabb849584366383a59d2ac985a7ece30609f1ae4a40ecfd02baad900a2d/capturer-2.4.tar.gz
Summary  : Easily capture stdout/stderr of the current process and subprocesses
Group    : Development/Tools
License  : MIT
Requires: capturer-license = %{version}-%{release}
Requires: capturer-python = %{version}-%{release}
Requires: capturer-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
capturer: Easily capture stdout/stderr of the current process and subprocesses
==============================================================================

%package license
Summary: license components for the capturer package.
Group: Default

%description license
license components for the capturer package.


%package python
Summary: python components for the capturer package.
Group: Default
Requires: capturer-python3 = %{version}-%{release}

%description python
python components for the capturer package.


%package python3
Summary: python3 components for the capturer package.
Group: Default
Requires: python3-core

%description python3
python3 components for the capturer package.


%prep
%setup -q -n capturer-2.4
cd %{_builddir}/capturer-2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582666291
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/capturer
cp %{_builddir}/capturer-2.4/LICENSE.txt %{buildroot}/usr/share/package-licenses/capturer/866edd19fb4956cbbd3c174ccdbeed6c392b30fc
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/capturer/866edd19fb4956cbbd3c174ccdbeed6c392b30fc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
